name: Dummy workflow

on:
  push:
    branches:
      - main


env:
  DESIGNITE_OUTPUT: ./designite-output-${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest      
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'corrretto'
      
      - name: Checkout
        uses: actions/checkout@v4
        
        
      - name: Run Designite
        id: designite
        run: |
            java --version
            echo "${{env.DESIGNITE_OUTPUT}}"
            java -jar ./.github/DesigniteJava.jar -i ./ -o "${{env.DESIGNITE_OUTPUT}}" -d
      
      - name: Archive Designite results
        uses: actions/upload-artifact@v3
        with:
          name: designite-output-${{ github.sha }}
          path: "${{env.DESIGNITE_OUTPUT}}"

      - name: Test Action
        uses: IP1102/designite-diff-action@4c1f54ee92e03ea6de1c7c527930a708bbff5cf6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          designite-output-old: designite-output-${{ github.event.before }}
          designite-output-new: designite-output-${{ github.sha }}
          repo-name: ${{ github.repository }}             

      - name: Verify
        run: ls -a ./

      